[package]
name = "video"
version = "0.1.0"
authors = ["Jeron Aldaron Lau <jeronlau@plopgrizzly.com>"]
edition = "2018"
build = "build.rs"

[dependencies.cala]
features = ["input", "draw", "pixels"]
path = "../../"

[build-dependencies]
res = "0.5"

[replace]
"res:0.5.0" = { path = "../../../res" }
